# Generated by Django 3.0.4 on 2020-03-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apellidos',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nombres',
            field=models.CharField(max_length=60),
        ),
    ]
