# Generated by Django 3.0.4 on 2020-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200309_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/Twitter_Logo_Blue.png', upload_to='images/'),
        ),
    ]
